title: Juan Chen's Homepage
page-top-title: Juan Chen
top-section-bg-text: Artificial Intelligence
home-subtitle: Juan Chen&ensp;|&ensp;陈铭辉
copyright-text: '&copy; Juan Chen 2025-2026. All Rights Reserved.'
